### ISSUE TITLE
Erros, when i try compile form last (trunk) branch

### ISSUE THREAD

**Issue by itProfi** [remakeelectric/owrt_pub_feeds#10]
Good day! When i try compile you feeds with fuul last openwrt, i get:
openwrt@openwrt-VirtualBox:~/lede/1043/openwrt$ make toolchain/install -j5 V=S
WARNING: Makefile 'package/feeds/owrt_pub_feeds/lsyslog/Makefile' has a build dependency on 'liblua', which does not exist
WARNING: Makefile 'package/feeds/owrt_pub_feeds/lua-libmodbus/Makefile' has a build dependency on 'liblua', which does not exist
WARNING: Makefile 'package/feeds/owrt_pub_feeds/lua-statsd/Makefile' has a build dependency on 'liblua', which does not exist
WARNING: Makefile 'package/feeds/owrt_pub_feeds/lualibusb1/Makefile' has a build dependency on 'liblua', which does not exist
make[2]: Entering directory '/home/openwrt/lede/1043/openwrt/scripts/config'
make[2]: Leaving directory '/home/openwrt/lede/1043/openwrt/scripts/config'
I attach my detail log file:
[make V=99 2>&1 | tee build.log | grep -i error.txt](https://github.com/remakeelectric/owrt_pub_feeds/files/1728683/make.V.99.2.1.tee.build.log.grep.-i.error.txt)

**Comment by karlp** [comment]
they're just warnings, do they matter? I'm building ok on current master.  (But I'm not seeing those warnings either)

**Comment by itProfi** [comment]
NO, absolutly not working...(

**Comment by karlp** [comment]
Ok, that's compeltely different :)  What package are you actually using this feed for?  it looks like you have only partially installed or something, you're trying to use mosquitto-next, but didnt' select libwebsockets?  are you building on openwrt master or the 17.01 branch? or?  I'll look more at this on monday.

**Comment by itProfi** [comment]
![18-02-2018 002837](https://user-images.githubusercontent.com/6728198/36345794-db267016-1442-11e8-8610-d9db2cc28147.jpg)
All work!!!

**Comment by karlp** [comment]
Ok, great :)
