### ISSUE TITLE
luci-app-mosquitto: support more options

### ISSUE THREAD

**Issue by itProfi** [remakeelectric/owrt_pub_feeds#11]
It's great feed, but i tnink, needed some configurable options for it :) :
1. Changable port of default listener
2. Authorization for default listener (user, password) - because without it, mosquitto becomes very vulnerable
3. I try oprion "**bridge_attempt_unsubscribe false**" manually, but when i send message from local client , it arrive for remote broker via bridge..But when i try send message from remote client to remote broker (back through the local bridge) message from remote client not arrived...
Like this:
![18-02-2018 090949](https://user-images.githubusercontent.com/6728198/36348925-a26b5b30-148b-11e8-92c6-fc6c4af07323.jpg)
Is it possible?
Also, i think, needed to :) add some information in read.me - about libwebsocket, about, mosquitto-next broker instead default mosquitto
P.S. I see, that you sometimes plans do about bridge configuration (in, out, both)...- https://github.com/remakeelectric/owrt_pub_feeds/blob/33cadceb2c5af565d96d5b65e2a982d492d0bd52/luci-app-mosquitto/luasrc/model/cbi/mosquitto.lua#L155

P.P.S:
What i do with this warnings until compile time?:
WARNING: Makefile 'package/feeds/owrt_pub_feeds/lsyslog/Makefile' has a build dependency on 'liblua', which does not exist
WARNING: Makefile 'package/feeds/owrt_pub_feeds/lua-libmodbus/Makefile' has a build dependency on 'liblua', which does not exist
WARNING: Makefile 'package/feeds/owrt_pub_feeds/lua-statsd/Makefile' has a build dependency on 'liblua', which does not exist
WARNING: Makefile 'package/feeds/owrt_pub_feeds/lualibusb1/Makefile' has a build dependency on 'liblua', which does not exist

**Comment by karlp** [comment]
Pull requests welcome.  Currently for bridges you just have to enter lines of text just like 
![screenshot from 2018-02-18 15-25-45](https://user-images.githubusercontent.com/127907/36353581-14ff2c74-14c0-11e8-888b-1a01722b7d6e.png)

I'm not planning on doing much development work myself on this, it meets our needs, but I'll happily help you make changes.

**Comment by itProfi** [comment]
ok. tnaks for answer.

**Comment by cconde** [comment]
Hello,

Thanks for this great work.

I'm looking forward to configure users and passwords (at least one) from luci.

I would be more than happy to help, but I have zero experience with LUA.
