### ISSUE TITLE
Not see mosquitto-next on precompile procedure..

### ISSUE THREAD

**Issue by itProfi** [remakeelectric/owrt_pub_feeds#12]
Hello! I see you add many other fields one day ago! Thanks! But today, i decide compile chaos_calmer from source. Turn on libwebsocket (openssl)..Not see mosquitto-next in Network...Try ./scripts/feeds uninstall mosquitto, then ./scripts/feeds install -p owrt_pub_feeds mosquitto..Not see nothing except mqttcollect...(

**Comment by karlp** [comment]
It's called mosquitto-next, not mosquitto.

**Comment by itProfi** [comment]
I know, that's called mosquitto-next, Not see mosquitto-next in Network...

**Comment by karlp** [comment]
If you'e actually added this feed, and installed from _this_ feed, then I can't help further I'm afraid.
