### ISSUE TITLE
submit luci-app-mosquitto to upstream luci

### ISSUE THREAD

**Issue by roger-** [remakeelectric/owrt_pub_feeds#13]
Any desire to submit luci-app-mosquitto to the official luci repo so packages can be auto-built?

**Comment by karlp** [comment]
Submit which?

**Comment by roger-** [comment]
Sorry I meant luci-app-mosquitto.

**Comment by karlp** [comment]
yeah, it woudl be good.  I maintain the mosquitto package anyway.  It's jsut been a matter of time.  Traditionally getting packages into the luci repo was extremeely slow, it's probably worht submitting now.  I'll get to it eventually, can't promise it this week though.  Thanks for the push!

**Comment by karlp** [comment]
(I actually even have a ticket in our internal tracking to do exactly this, from a while ago, fwiw :)

**Comment by roger-** [comment]
Awesome thanks! I’m sure lots of people would also appreciate having the package be more accessible. Your pagekite LuCi app is probably a good candidate too. 


Nowadays it’s pretty quick to get pills accepted on GitHub: https://github.com/openwrt/luci/pulls

**Comment by karlp** [comment]
follow along at  https://github.com/openwrt/luci/pull/2160

**Comment by karlp** [comment]
for ref, this had been originally submitted as http://luci.subsignal.org/trac/ticket/435

**Comment by karlp** [comment]
(luci-app-pagekite is already in upstream, it's here still just so that you can build it on older trees if needed)
