### ISSUE TITLE
mosquito: does not compile for me

### ISSUE THREAD

**Issue by Gibol** [remakeelectric/owrt_pub_feeds#5]
in makefile:
define Package/$(PKG_NAME)/conffiles
/etc/mosquitto/mosquitto.conf
/etc/config/mosquitto
endef

make yelds:
**\* Error: CONTROL/conffiles mentions conffile /etc/config/mosquitto which does not exist

after deleting "/etc/config/mosquitto" it finishes with success.

**Comment by karlp** [comment]
What rev of OpenWrt are you building?  I presume trunk/CC ? Mosquitto itself is in the main http://github.com/openwrt/packages repository now (where I'm the maintainer) I presume they added some more validation and enforcement of these file listings.  The init script I package can use the /etc/config/mosquitto file if it exists, so it should be preserved if it exists, I'll have to chase the openwrt devs on the "right" way of solving this, but it will probably be by including a sample /etc/config/mosquitto file with the enable flag off so it uses the stock file by default.

**Comment by karlp** [comment]
Are you still seeing this? I built trunk again for the 1.4.1 release and it still builds clean for me.

**Comment by karlp** [comment]
no new information, old ticket
