### ISSUE TITLE
mosquitto 1.4 available now!

### ISSUE THREAD

**Issue by Suxsem** [remakeelectric/owrt_pub_feeds#6]

**Comment by karlp** [comment]
Yep, I know, working on this today, was travelling earlier this week unfortunately.

**Comment by Suxsem** [comment]
Great, thanks :)

**Comment by karlp** [comment]
Both this repository, and upstream openwrt (for trunk) have been updated to mosquitto 1.4

**Comment by Suxsem** [comment]
many thanks, waiting for nighly build :smiley: 
anyway, it's CONFIG_MOSQUITTO_LWS on by default?

**Comment by karlp** [comment]
You can look at the commits for this... https://github.com/remakeelectric/owrt_pub_feeds/commit/e7f2c9b217402a3dba8100ab1b9a0d0f90784bb1

**Comment by Suxsem** [comment]
great, thanks :)
