### ISSUE TITLE
14.07 Missing  libwebsockets.so.8

### ISSUE THREAD

**Issue by oblivionangel** [remakeelectric/owrt_pub_feeds#9]
error occurs when i am compiling the trunk.
I also selected libwebsocket to build, but it doesn't help.
Can you tell me what did I missing?

**Comment by karlp** [comment]
I'm not testing, nor attempting to maintain libwebsockets for BB-14.07 branch anymore, I'll update the readme, and if you have any patch that will make it work on BB again, I'll accept them.

I'm afraid your message doesn't really have any details to say anything further though.  But note that so.8 is for libwebsockets 2.x, which is not provided in this feed.

**Comment by oblivionangel** [comment]
Mhhhh, you closed the issue.
I found the feasible patch in newest mosquitto version 1.4.10.
0001-websockets-fix-compatibility-with-older-lws-versions

perhaps it wouble be better you update your branch?

**Comment by karlp** [comment]
Update what? Is your issue with mosquitto or libwebsockets?  Both of those packages are available and maintained upstream, for both CC and trunk.  I'm not maintaining BB anymore, but if you have patches to make things work with BB I'll merged them, as I said.  The mosquitto package in this feed is already 1.4.10.
